services:
  app:
    build: .
    container_name: springboot-app-RetoDaw
    ports:
      - "5001:5000"  # Aquí mapeas el puerto 5000 dentro del contenedor a 5001 en el host
    depends_on:
      - mariadbreto
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3307/vacantes_BBDD_2025_RETO
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: joseluis
    networks:
      - RetoDaw-network
    command: ["./wait-for-it.sh", "host.docker.internal:3307", "--", "java", "-jar", "RetoDaw.war"]
    # Este comando espera a la base de datos MariaDB para asegurarse de que esté lista antes de ejecutar la app

networks:
  RetoDaw-network: {}
